import Head from "next/head";
import React from "react";
import Blogs from "../../components/Blogs/Blogs";

const index = () => {
  return (
    <>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <Blogs />
    </>
  );
};

export default index;
