import React from "react";
import TejasRavishankarAvatar from "../../public/images/Investors/tejas-ravishankar.svg";
import Link from "next/link";
import Blog from "../../components/Blog/Blog";
import BlogImage from "../../components/Blog/components/Image/BlogImage";
import Paragraph from "../../components/Blog/components/Paragraph/Paragraph";
import { People } from "../../data/investorsInfo";
import BlogImage1 from "../../public/images/Blog/blog-image-1.png";
import Head from "next/head";
import BlogCodeComponent from "../../components/Blog/components/Code/BlogCodeComponent";

let quote = {
  text: "“Dimension is solving for one of the biggest problems in the development space and I’m excited to join them in their journey!”",
  by: "Tom Preston-Werner, Co-Founder of GitHub",
};

const index = () => {
  return (
    <div>
      {" "}
      <Head>
        <title>Blog | Pre-Seed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Blog
        title="Blog title"
        subheading="sub-heading"
        description="description"
        writer="Tejas Ravishankar"
        writerAvatar={TejasRavishankarAvatar}
        publishedDate="12th December 2022"
        socialLink="https://twitter.com/suptejas"
      >
        <BlogImage
          caption="Manage your projects on Dimension."
          src={BlogImage1}
          alt="Blog image"
        />
        <Paragraph
          text={
            <>
              We believe software development is broken today, millions of
              tools, hundreds of tabs, and a lack of integration results in a
              slow, <Link href={"#"}>This is a link</Link>{" "}
              <strong>painful</strong> development process and a poor developer
              experience.
              <br />
              <p>
                We believe software development is broken today, millions of
                tools, hundreds of tabs, and a lack of integration results in a
              </p>
            </>
          }
          heading="The Problem"
        />
        <Paragraph heading="Heading #2" quote={quote} />
        <Paragraph
          heading="Heading #2"
          style={{ marginTop: "1.2rem" }}
          people={People}
        />
        <BlogCodeComponent
          language="javascript"
          code={`          import Image, { StaticImageData } from "next/image";
          import Link from "next/link";
          import React from "react";
          import classes from "./Blog.module.scss";
          
          type BlogPropsType = {
            children?: React.ReactNode;
            title: string;
            description: string;
            subheading: string;
            writer: string;
            writerAvatar: StaticImageData;
            publishedDate: string;
            socialLink: string;
          };
          
          const Blog: React.FC<BlogPropsType> = (props) => {
            const {
              title,
              description,
              subheading,
              publishedDate,
              writer,
              writerAvatar,
              socialLink,
            } = props;
          
            return (
              <div className={classes.blog__outer}>
                <div className={classes.blog}>
                  <div className={classes.blog__info}>
                    <h1 className={classes.blog__info__heading}>{title}</h1>
                    <h3 className={classes.blog__info__subheading}>
                      {subheading}/{description}
                    </h3>
                    <div className={classes.blog__info__writer}>
                      <Link target={"_blank"} href={socialLink}>
                        <Image
                          width={24}
                          height={24}
                          src={writerAvatar}
                          alt="Profile Pciture"
                        />
                        {writer}
                      </Link>
                      <span></span>
                      <span>{publishedDate}</span>
                    </div>
                  </div>
                  {props.children}
                </div>
              </div>
            );
          };
          
          export default Blog;
          `}
        />
      </Blog>
    </div>
  );
};

export default index;
