import Head from "next/head";
import TejasRavishankarAvatar from "../public/images/Investors/tejas-ravishankar.svg";
import Link from "next/link";
import Blog from "../components/Blog/Blog";
import BlogImage from "../components/Blog/components/Image/BlogImage";
import Paragraph from "../components/Blog/components/Paragraph/Paragraph";
import { People } from "../data/investorsInfo";
import BlogImage1 from "../public/images/Blog/blog-image-1.png";
import Hero from "../components/HeroSections/Hero";
import Blogs from "../components/Blogs/Blogs";

let quote = {
  text: "“Dimension is solving for one of the biggest problems in the development space and I’m excited to join them in their journey!”",
  by: "Tom Preston-Werner, Co-Founder of GitHub",
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Dimension</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Blogs />
    </>
  );
}
